Exhibit bug for #794
You can run
```bash
./autogen.sh && COQBIN="/path/to/coq/bin/" ./configure && make clean && make TIMED=1 -kj theories/bug_csu_slow_tc_01.vo
```
You'll need to change `simple refine` to `refine` in `bug_csu_slow_tc_01.v` to
get it to build with 8.5beta2, but everything other than that should build fine
with both 8.5beta2 and 8.5.
On my machine, I get, with 8.5beta2:
```
HOQC theories/bug_csu_slow_tc_01
Finished transaction in 3.246 secs (3.248u,0.s) (successful)
Finished transaction in 0.533 secs (0.532u,0.s) (successful)
Finished transaction in 3.208 secs (3.208u,0.s) (successful)
Finished transaction in 1.268 secs (1.267u,0.s) (successful)
Finished transaction in 3.182 secs (3.184u,0.s) (successful)
Finished transaction in 0.528 secs (0.527u,0.s) (successful)
Finished transaction in 3.159 secs (3.16u,0.s) (successful)
Error: There are pending proofs
Command exited with non-zero status 1
theories/bug_csu_slow_tc_01 (user: 16.72 mem: 319720 ko)
make: *** [theories/bug_csu_slow_tc_01.vo] Error 1
```
with 8.5 released:
```
HOQC theories/bug_csu_slow_tc_01
Finished transaction in 4.71 secs (4.712u,0.s) (successful)
Finished transaction in 4.219 secs (4.22u,0.s) (successful)
Finished transaction in 4.632 secs (4.632u,0.s) (successful)
Finished transaction in 13.448 secs (13.444u,0.008s) (successful)
Finished transaction in 4.681 secs (4.68u,0.s) (successful)
Finished transaction in 4.22 secs (4.219u,0.s) (successful)
Finished transaction in 4.616 secs (4.612u,0.004s) (successful)
File "./theories/bug_csu_slow_tc_01.v", line 296, characters 4-26:
Timeout!
Command exited with non-zero status 1
theories/bug_csu_slow_tc_01 (user: 44.86 mem: 336200 ko)
make: *** [theories/bug_csu_slow_tc_01.vo] Error 1
```